import {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Banknote,
  BookKey,
  Boxes,
  Building2,
  Calendar,
  Check,
  Eye,
  EyeOff,
  FileQuestion,
  FileWarning,
  Hourglass,
  Import,
  KeyRound,
  List,
  Mail,
  Menu,
  Phone,
  Package,
  Plus,
  Search,
  ShoppingBag,
  Trash2,
  User,
  Wrench,
  Truck,
  Pencil,
  X,
  ClipboardList,
  Users,
  FilePlus2,
  Handshake,
  BriefcaseConveyorBelt,
  Settings,
  Home,
  Inbox,
  ChevronsUpDown,
  CalendarIcon,
  GalleryVerticalEnd,
  AudioWaveform,
  Command,
  SquareTerminal,
  Bot,
  BookOpen,
  Settings2,
  LogOut,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  AlignLeft,
  AlignCenter,
  AlignJustify,
  AlignRight,
  ListOrdered,
  LockOpen,
  Lock,
  Archive,
  CircleCheck,
  File,
  FileDigit,
  ChevronsLeft,
  ChevronsRight,
  Link,
  CircleHelp,
} from 'lucide-react'

const icons = (size = 4) => ({
  eye: <Eye className={`h-${size} w-${size}`} />,
  eyeOff: <EyeOff className={`h-${size} w-${size}`} />,
  key: <KeyRound className={`h-${size} w-${size}`} />,
  plus: <Plus className={`h-${size} w-${size}`} />,
  user: <User className={`h-${size} w-${size}`} />,
  arrowRight: <ArrowRight className={`h-${size} w-${size}`} />,
  arrowDown: <ArrowDown className={`h-${size} w-${size}`} />,
  arrowLeft: <ArrowLeft className={`h-${size} w-${size}`} />,
  arrowUp: <ArrowUp className={`h-${size} w-${size}`} />,
  check: <Check className={`h-${size} w-${size}`} />,
  pencil: <Pencil className={`h-${size} w-${size}`} />,
  list: <List className={`h-${size} w-${size}`} />,
  menu: <Menu className={`h-${size} w-${size}`} />,
  x: <X className={`h-${size} w-${size}`} />,
  trash: <Trash2 className={`h-${size} w-${size}`} />,
  calendar: <Calendar className={`h-${size} w-${size}`} />,
  boxes: <Boxes className={`h-${size} w-${size}`} />,
  package: <Package className={`h-${size} w-${size}`} />,
  shoppingBag: <ShoppingBag className={`h-${size} w-${size}`} />,
  wrench: <Wrench className={`h-${size} w-${size}`} />,
  truck: <Truck className={`h-${size} w-${size}`} />,
  banknote: <Banknote className={`h-${size} w-${size}`} />,
  fileQuestion: <FileQuestion className={`h-${size} w-${size}`} />,
  fileWarning: <FileWarning className={`h-${size} w-${size}`} />,
  building: <Building2 className={`h-${size} w-${size}`} />,
  mail: <Mail className={`h-${size} w-${size}`} />,
  bookKey: <BookKey className={`h-${size} w-${size}`} />,
  search: <Search className={`h-${size} w-${size}`} />,
  hourglass: <Hourglass className={`h-${size} w-${size}`} />,
  import: <Import className={`h-${size} w-${size}`} />,
  phone: <Phone className={`h-${size} w-${size}`} />,
  clipboardList: <ClipboardList className={`h-${size} w-${size}`} />,
  users: <Users className={`h-${size} w-${size}`} />,
  filePlus: <FilePlus2 className={`h-${size} w-${size}`} />,
  handshake: <Handshake className={`h-${size} w-${size}`} />,
  briefcaseConveyorBelt: (
    <BriefcaseConveyorBelt className={`h-${size} w-${size}`} />
  ),
  settings: <Settings className={`h-${size} w-${size}`} />,
  home: <Home className={`h-${size} w-${size}`} />,
  inbox: <Inbox className={`h-${size} w-${size}`} />,
  chevronsUpDown: <ChevronsUpDown className={`h-${size} w-${size}`} />,
  calendarIcon: <CalendarIcon className={`h-${size} w-${size}`} />,
  galleryVerticalEnd: <GalleryVerticalEnd className={`h-${size} w-${size}`} />,
  audioWaveform: <AudioWaveform className={`h-${size} w-${size}`} />,
  command: <Command className={`h-${size} w-${size}`} />,
  squareTerminal: <SquareTerminal className={`h-${size} w-${size}`} />,
  bot: <Bot className={`h-${size} w-${size}`} />,
  bookOpen: <BookOpen className={`h-${size} w-${size}`} />,
  settings2: <Settings2 className={`h-${size} w-${size}`} />,
  logOut: <LogOut className={`h-${size} w-${size}`} />,
  bold: <Bold className={`h-${size} w-${size}`} />,
  italic: <Italic className={`h-${size} w-${size}`} />,
  underline: <Underline className={`h-${size} w-${size}`} />,
  strikethrough: <Strikethrough className={`h-${size} w-${size}`} />,
  alignLeft: <AlignLeft className={`h-${size} w-${size}`} />,
  alignCenter: <AlignCenter className={`h-${size} w-${size}`} />,
  alignRight: <AlignRight className={`h-${size} w-${size}`} />,
  alignJustify: <AlignJustify className={`h-${size} w-${size}`} />,
  listOrdered: <ListOrdered className={`h-${size} w-${size}`} />,
  lock: <Lock className={`h-${size} w-${size}`} />,
  lockOpen: <LockOpen className={`h-${size} w-${size}`} />,
  archive: <Archive className={`h-${size} w-${size}`} />,
  circleCheck: <CircleCheck className={`h-${size} w-${size}`} />,
  file: <File className={`h-${size} w-${size}`} />,
  fileDigit: <FileDigit className={`h-${size} w-${size}`} />,
  settingsTable: <Settings2 className={`h-${size} w-${size}`} />,
  chevronsLeft: <ChevronsLeft className={`h-${size} w-${size}`} />,
  chevronsRight: <ChevronsRight className={`h-${size} w-${size}`} />,
  link: <Link className={`h-${size} w-${size}`} />,
  circleHelp: <CircleHelp className={`h-${size} w-${size}`} />,
})

export { icons }
