import {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Banknote,
  BookKey,
  Boxes,
  Building2,
  Calendar,
  Check,
  Eye,
  EyeOff,
  FileQuestion,
  FileWarning,
  Hourglass,
  Import,
  KeyRound,
  List,
  Mail,
  Menu,
  Package,
  Pencil,
  Plus,
  Search,
  ShoppingBag,
  Trash2,
  Truck,
  User,
  Wrench,
  X,
} from 'lucide-react'

export const icons = {
  eye: <Eye className="h-4 w-4" />,
  eyeOff: <EyeOff className="h-4 w-4" />,
  key: <KeyRound className="h-4 w-4" />,
  plus: <Plus className="h-4 w-4" />,
  user: <User className="h-4 w-4" />,
  arrowRight: <ArrowRight className="h-4 w-4" />,
  arrowDown: <ArrowDown className="h-4 w-4" />,
  arrowLeft: <ArrowLeft className="h-4 w-4" />,
  arrowUp: <ArrowUp className="h-4 w-4" />,
  check: <Check className="h-4 w-4" />,
  pencil: <Pencil className="h-4 w-4" />,
  list: <List className="h-4 w-4" />,
  menu: <Menu className="h-4 w-4" />,
  x: <X className="h-4 w-4" />,
  trash: <Trash2 className="h-4 w-4" />,
  calendar: <Calendar className="h-4 w-4" />,
  boxes: <Boxes className="h-4 w-4" />,
  package: <Package className="h-4 w-4" />,
  shoppingBag: <ShoppingBag className="h-4 w-4" />,
  wrench: <Wrench className="h-4 w-4" />,
  truck: <Truck className="h-4 w-4" />,
  banknote: <Banknote className="h-4 w-4" />,
  fileQuestion: <FileQuestion className="h-4 w-4" />,
  fileWarning: <FileWarning className="h-4 w-4" />,
  building: <Building2 className="h-4 w-4" />,
  mail: <Mail className="h-4 w-4" />,
  bookKey: <BookKey className="h-4 w-4" />,
  search: <Search className="h-4 w-4" />,
  hourglass: <Hourglass className="h-4 w-4" />,
  import: <Import className="h-4 w-4" />,
}
